name = "quranlounge"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

# KV Namespace binding for token and data caching
[[kv_namespaces]]
binding = "QURAN_CACHE"
id = "d601ae5713af43deab1dae4885cbcdc3"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "quran-lounge"
